### ISSUE TITLE
@property char group; 尽量不要这么写，写完整

### ISSUE THREAD

**Issue by maintiendrai** [falcon11/address_contact_ios#2]

**Comment by maintiendrai** [comment]
在iOS开发中，你会发现，几乎所有属性都声明为 nonatomic。如果没有写，默认是atomic，atomic该属性使用了同步锁，会在创建时生成一些额外的代码用于帮助编写多线程程序，这会带来性能问题，通过声明 nonatomic 可以节省这些虽然很小但是不必要额外开销。

**Comment by falcon11** [comment]
已修改
