### ISSUE TITLE
注意分层，请理解MVC

### ISSUE THREAD

**Issue by smallmuou** [falcon11/address_contact_ios#5]
UIAlertView *ConnectionFailed = [[UIAlertView alloc]
                                     initWithTitle:@"Connection Failed"
                                     message: [NSString stringWithFormat:@"%@", [error localizedDescription]]
                                     delegate:self
                                     cancelButtonTitle:@"Ok"
                                     otherButtonTitles:nil];
    [ConnectionFailed show];

（1）HttpService不应该直接进行UI提示，否则可复用性太低.
（2）变量名不规范，ConnectionFailed，一般只有类型名，首字母才大写
  (3) http错误需往上一层传递，以便上一层做相应的处理

**Comment by falcon11** [comment]
好吧，我弄个通知。

**Comment by maintiendrai** [comment]
。。。还是被说了
